### ISSUE TITLE
Cleanup Meetings Repo

### ISSUE THREAD

**Issue by Cosmo801** [TinBryn/Molecule-of-the-Month#23]
- [ ] Rename the meeting files so that they share a format
- e.g. Meetings: Meeting 9/28 Minutes
- e.g. Auditor: Auditor Meeting 9/28 Minutes
- e.g. Mentor: Mentor Meeting 9/28 Minutes
- [ ] If possible, try and find any meetings that may be missing (use teams or slack history?)

**Comment by TinBryn** [comment]
I could do this

**Comment by TinBryn** [comment]
It looks like @danielgerardclaassen is already doing this.

**Comment by danielgerardclaassen** [comment]
Added a missing meeting and reformatted all titles. Also deleted now irrelevant 'meetings' branch that only contained redundancies.

**Comment by TinBryn** [comment]
Having it done with all of those commits makes it difficult to track what files got renamed. I have an alternative that does it in a single commit.

**Comment by danielgerardclaassen** [comment]
More power to you.

**Comment by danielgerardclaassen** [comment]
Just remember I added a file, a mentor meeting on the 28/09
