### ISSUE TITLE
Start work on conversion system 

### ISSUE THREAD

**Issue by TinBryn** [TinBryn/Molecule-of-the-Month#6]
The file conversion from chemical files to 3D models should happen on the app, since this is a browser based app that needs to happen in JavaScript or something that compiles to js or wasm such as TypeScript to js.

**Comment by Cosmo801** [comment]
Handle conversion code here https://github.com/TinBryn/Molecule-of-the-Month/blob/master/convertor/convertor.js on a new branch

**Comment by TinBryn** [comment]
We found a library on npm called "pdb-parse" which sounds like it does exactly what we want, turns a .pdb file into a javascript object with fields representing atoms, bonds and any metadata. The problem is that it's fairly incomplete and only handles a small subset of the spec and parses our example molecule files as empty.

Looking into the details of the library it's all done using 85 lines of code and it doesn't even have any dependencies. It actually works really well on the subset that it is implemented for, so it shouldn't be too hard to extend it to support a wider portion of the pdb spec.

**Comment by Cosmo801** [comment]
Closing this and creating some more specific issues for the converter
